version: '3.3'

services:
  postgres:
    build:
      context: ./data/postgres
    image: postgres:9.6
    container_name: spree_postgres
    hostname: postgres
    env_file: .env
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/spree/data

volumes:
  postgres_data:
    driver: local
